version: '3.3'
networks:
  jina-network:
    driver: bridge
services:
  gateway:
    image: registry.hubble.jina.ai/executors/k7xuf1u1:65f145ce314167b2aba55667
    entrypoint:
    - jina
    command:
    - gateway
    - --expose-endpoints
    - '{}'
    - --uses
    - HTTPGateway
    - --deployments-addresses
    - '{}'
    - --port
    - '8080'
    - --protocol
    - HTTP
    - --port-monitoring
    - '54351'
    expose:
    - 8080
    ports:
    - 8080:8080
    healthcheck:
      test: jina ping gateway http://127.0.0.1:8080
      interval: 2s
    environment:
    - JINA_LOG_LEVEL=INFO
    networks:
    - jina-network
